### ISSUE TITLE
When we use __global_action in our config updates, we will run into the following error

### ISSUE THREAD

**Issue by Natshah** [Vardot/module-update_helper#1]
Using the latest patch at
patch in
https://www.drupal.org/project/update_helper/issues/3024165

As we added 
_global_actions:
 install_modules:
   - length_indicator

__global_actions:
 install_modules:
   - varbase_email

We will have the issue after
https://github.com/Vardot/varbase_core/commit/06dbc27872660380c3e21345a734ca96a329e24c

Switching back until we have a new patch or the parted patches

```[Mon May 06 14:23:58.604981 2019] [php7:notice] [pid 32385] [client ::1:60358] TypeError: Argument 3 passed to Drupal\\update_helper\\Updater::updateConfig() must be of the type array, null given, called in /var/www/html/dev/varbase6c/docroot/modules/contrib/update_helper/src/Updater.php on line 236 in /var/www/html/dev/varbase6c/docroot/modules/contrib/update_helper/src/Updater.php on line 384 #0 /var/www/html/dev/varbase6c/docroot/modules/contrib/update_helper/src/Updater.php(236): Drupal\\update_helper\\Updater->updateConfig('__global_action...', Array, NULL, Array, false, true)\n#1 /var/www/html/dev/varbase6c/docroot/modules/contrib/update_helper/src/Updater.php(176): Drupal\\update_helper\\Updater->executeConfigurationActions(Array, false, true)\n#2 /var/www/html/dev/varbase6c/docroot/modules/contrib/update_helper/modules/update_helper_checklist/update_helper_checklist.module(155): Drupal\\update_helper\\Updater->checkUpdate('varbase_core', 'varbase_email_e...')\n#3 [internal function]: update_helper_checklist_modules_installed(Array)\n#4 /var/www/html/dev/varbase6c/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php(403): call_user_func_array('update_helper_c...', Array)\n#5 /var/www/html/dev/varbase6c/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(325): Drupal\\Core\\Extension\\ModuleHandler->invokeAll('modules_install...', Array)\n#6 /var/www/html/dev/varbase6c/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, true)\n#7 /var/www/html/dev/varbase6c/docroot/profiles/varbase/varbase.profile(362): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, true)\n#8 /var/www/html/dev/varbase6c/docroot/core/includes/batch.inc(295): varbase_assemble_extra_component_then_install('varbase_update_...', Array)\n#9 /var/www/html/dev/varbase6c/docroot/core/includes/batch.inc(137): _batch_process()\n#10 /var/www/html/dev/varbase6c/docroot/core/includes/batch.inc(93): _batch_do()\n#11 /var/www/html/dev/varbase6c/docroot/core/includes/install.core.inc(678): _batch_page(Object(Symfony\\Component\\HttpFoundation\\Request))\n#12 /var/www/html/dev/varbase6c/docroot/core/includes/install.core.inc(583): install_run_task(Array, Array)\n#13 /var/www/html/dev/varbase6c/docroot/core/includes/install.core.inc(118): install_run_tasks(Array, NULL)\n#14 /var/www/html/dev/varbase6c/docroot/core/install.php(44): install_drupal(Object(Composer\\Autoload\\ClassLoader))\n#15 {main}, referer: http://localhost/dev/varbase6c/docroot/core/install.php?rewrite=ok&profile=varbase&langcode=en&id=3&op=start```

**Comment by waleedq** [comment]
Hello Rajab, 

i've pushed a new fix for this issue. Please check it out and let me know if you still face any issues.

Thank you.

**Comment by Natshah** [comment]
Thank you :)
